hw10_web/project_quotes/app_quotes/urls.py
from django.urls import path
from . import views

app_name = 'app_quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('about_author/<int:author_id>', views.about_author, name='about_author'),
    path('tag/', views.tag, name='tag'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete')
]

hw10_web/project_quotes/project_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_quotes.urls')),
    path('users/', include('users.urls')),
]

hw10_web/project_quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

hw10_web/project_quotes/app_quotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Модель для тегів, які можна прикріплювати до цитат
class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f'{self.name}'


# Модель для збереження інформації про авторів цитат
class Author(models.Model):
    fullname = models.CharField(null=False, unique=True)
    born_date = models.CharField()
    born_location = models.CharField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.fullname}'


# Модель для збереження самих цитат
class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    quote = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.quote}'

hw10_web/project_quotes/app_quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField
from .models import Tag, Author, Quote


# Форма для створення або редагування тегів
class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


# Форма для створення або редагування авторів
class AuthorForm(ModelForm):
    fullname = CharField(min_length=3, required=True, widget=TextInput())
    born_date = CharField(min_length=3, required=True, widget=TextInput())
    born_location = CharField(min_length=3, required=True, widget=TextInput())
    description = CharField(min_length=3, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


# Форма для створення або редагування цитат
class QuoteForm(ModelForm):
    quote = CharField(min_length=10, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['author', 'tags']

hw10_web/project_quotes/app_quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Quote, Author, Tag


# Головна сторінка — виводить всі цитати
def main(request):
    quotes_list = Quote.objects.all()
    context = {'quotes_list': quotes_list}
    return render(request, 'app_quotes/index.html', context)


# Додавання автора (тільки для авторизованих користувачів)
@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect(to='app_quotes:main')
        else:
            return render(request, 'app_quotes/author.html', {'form': form})

    return render(request, 'app_quotes/author.html', {'form': AuthorForm()})


# Додавання цитати (тільки для авторизованих користувачів)
@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            quote_author = Author.objects.filter(fullname=request.POST['authors']).first()
            new_quote.author = quote_author
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            '''
            for tag in request.POST.getlist('tags'):
                quote_tag = Tag.objects.filter(name=tag).first()
                new_quote.tags.add(quote_tag)
            '''
            return redirect(to='app_quotes:main')
        else:
            return render(request, 'app_quotes/quote.html', {"authors": authors, "tags": tags, 'form': form})

    return render(request, 'app_quotes/quote.html', {"authors": authors, "tags": tags, 'form': QuoteForm()})


# Сторінка з інформацією про конкретного автора
def about_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'app_quotes/about_author.html', {"author": author})


# Додавання тегу (тільки для авторизованих користувачів)
@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='app_quotes:main')
        else:
            return render(request, 'app_quotes/tag.html', {'form': form})

    return render(request, 'app_quotes/tag.html', {'form': TagForm()})


# Видалення цитати за ID (тільки для авторизованих)
@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='app_quotes:main')

hw10_web/project_quotes/app_quotes/templates/app_quotes/about_author.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h1>{{author.fullname}}</h1>
<p>Дата народження: <b>{{author.born_date}}</b></p>
<p>Країна: <b>{{author.born_location}}</b></p>
<p>Опис: <b>{{author.description}}</b></p>

{% endblock %}

hw10_web/project_quotes/app_quotes/templates/app_quotes/author.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2> Додати автора </h2>
<form method="POST" action="{% url 'app_quotes:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Ім'я автора:
            {{form.fullname}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Дата народження:
            {{form.born_date}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Країна:
            {{form.born_location}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Опис:
            {{form.description}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Підтвердити</button>
        <button type="reset" class="secondary">Скасувати</button>
    </div>
</form>

{% endblock %}

hw10_web/project_quotes/app_quotes/templates/app_quotes/base.html
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_quotes/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <h1>
            <a href="/" style="text-decoration: none">Цитати </a>
        </h1>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

hw10_web/project_quotes/app_quotes/templates/app_quotes/index.html
{% extends "app_quotes/base.html" %} {% block content %}

<nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
    <li><a href="tag/" role="button"> Додати тег </a></li>
    <li><a href="author/" role="button"> Додати автора </a></li>
    <li><a href="quote/" role="button"> Додати цитату </a></li>
    </ul>
    <ul>
        <li>Вітаю, <b>{{ user.username }}!</b></li>
        <li><a href="{% url 'users:logout' %}" role="button">Вийти</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Зареєстуватись</a></li>
        <li><a href="{% url 'users:login' %}" role="button">Увійти</a></li>
    </ul>
    {% endif %}
</nav>


<div class="row">
    <div class="quotes_list">
        {% if quotes_list %}
            {% for quote in quotes_list %}
                <div class="quote">
                    <p>Цитата: {{ quote.quote }}</p>
                    <p>Автор: <a href="about_author/{{quote.author.id}}">{{ quote.author.fullname }}</a></p>
                </div>
                <hr/>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

hw10_web/project_quotes/app_quotes/templates/app_quotes/quote.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2> Додати цитату </h2>

<form method="POST" action="{% url 'app_quotes:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Цитата:
            {{form.quote}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Виберіть автора:
            <select name="authors" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Виберіть теги:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Підтвердити</button>
        <button type="reset" class="secondary">Скасувати</button>
    </div>
</form>
{% endblock %}

hw10_web/project_quotes/app_quotes/templates/app_quotes/tag.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2> Додати тег </h2>
<form method="POST" action="{% url 'app_quotes:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Введіть назву тегу:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Підтвердити</button>
        <button type="reset" class="secondary">Скасувати</button>
    </div>
</form>

{% endblock %}